### ISSUE TITLE
Error: Must provide valid Document AST.

### ISSUE THREAD

**Issue by jasonkuhrt** [remorses/genql#20]
I don't see the problem. 

Version:

```json
    "genql-runtime": "^1.1.11",
    "genql-cli": "^1.1.11",
```

Schema:

```graphql
### This file was generated by Nexus Schema
### Do not make changes to this file directly


type Query {
  users: [User!]
}

"""foobar"""
type User {
  id: ID
  name: String
}
```

Output:

<details>
<summary>show</summary>

```
❯ npm run generate:client                  

> hello-world@1.0.0 generate:client /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world
> genql --schema api.graphql --output client

[15:02:35] generating the client in `client` [started]
[15:02:35] loading schema [started]
[15:02:35] loading schema [failed]
[15:02:35] → Must provide valid Document AST.
[15:02:35] preparing client directory [started]
[15:02:35] preparing client directory [completed]
[15:02:35] writing files [started]
[15:02:35] writing schema.graphql [started]
[15:02:35] writing schema.ts [started]
[15:02:35] writing guards.esm.js [started]
[15:02:35] writing guards.cjs.js [started]
[15:02:35] writing types.json [started]
[15:02:35] writing index.js [started]
[15:02:35] writing index.esm.js [started]
[15:02:35] writing index.d.ts [started]
[15:02:36] writing schema.graphql [failed]
[15:02:36] → Cannot read property 'getDirectives' of undefined
[15:02:36] writing schema.ts [failed]
[15:02:36] → Cannot read property 'getTypeMap' of undefined
[15:02:36] writing guards.esm.js [failed]
[15:02:36] → Cannot read property 'getTypeMap' of undefined
[15:02:36] writing guards.cjs.js [failed]
[15:02:36] → Cannot read property 'getTypeMap' of undefined
[15:02:36] writing types.json [failed]
[15:02:36] → Cannot read property 'getTypeMap' of undefined
[15:02:36] writing index.d.ts [failed]
[15:02:36] → Cannot read property 'getQueryType' of undefined
[15:02:36] writing files [failed]
[15:02:36] → Cannot read property 'getDirectives' of undefined
[15:02:36] generating the client in `client` [failed]
ListrError: Something went wrong
    at /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/listr/index.js:102:18 {
  name: 'ListrError',
  errors: [
    Error: Must provide valid Document AST.
        at devAssert (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/node_modules/graphql/jsutils/devAssert.js:12:11)
        at Object.buildASTSchema (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/node_modules/graphql/utilities/buildASTSchema.js:42:94)
        at /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/schemaTask.js:43:37
        at Generator.next (<anonymous>)
        at fulfilled (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/schemaTask.js:5:58),
    TypeError: Cannot read property 'getDirectives' of undefined
        at printFilteredSchema (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/node_modules/graphql/utilities/printSchema.js:54:27)
        at Object.printSchema (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/node_modules/graphql/utilities/printSchema.js:40:10)
        at Object.exports.renderSchema (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/render/schema/renderSchema.js:6:32)
        at /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/clientTasks.js:44:32
        at Generator.next (<anonymous>)
        at /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/clientTasks.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/clientTasks.js:4:12)
        at Task.task (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/genql-cli/dist/tasks/clientTasks.js:42:28)
        at /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/listr/lib/task.js:167:30 {
      context: [Object: null prototype] {}
    }
  ],
  context: [Object: null prototype] {}
}
```

</details>

**Comment by remorses** [comment]
That error means there is no `api.graphql` in the current directory, check that you are calling the command from the right directory

I am improving the error message in next version

**Comment by jasonkuhrt** [comment]
```
~/projects/graphql-nexus/examples/hello-world genql
❯ cat api.graphql
### This file was generated by Nexus Schema
### Do not make changes to this file directly


type Query {
  users: [User!]
}

"""foobar"""
type User {
  id: ID
  name: String
}

~/projects/graphql-nexus/examples/hello-world genql
❯ yarn genql --schema api.graphql --output client
yarn run v1.22.4
$ /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/.bin/genql --schema api.graphql --output client

<eventually error>
```

Repro available here https://github.com/graphql-nexus/examples/blob/genql/hello-world/package.json#L24

**Comment by remorses** [comment]
it woks fine for me, try reinstalling with latest version

**Comment by jasonkuhrt** [comment]
Thanks, thought I did that before. Different error now:

```
~/projects/graphql-nexus/examples/hello-world genql 7s
❯ ./node_modules/.bin/genql --schema api.graphql --output client
Something went wrong

~/projects/graphql-nexus/examples/hello-world genql
❯ cat api.graphql
### This file was generated by Nexus Schema
### Do not make changes to this file directly


type Query {
  users: [User!]
}

"""foobar"""
type User {
  id: ID
  name: String
}
```

**Comment by remorses** [comment]
it was a bug with duplicate graphql dependency, i had to use npm to reproduce

fixed in latest version

**Comment by jasonkuhrt** [comment]
I think that's the second npm issue :D As a yarn user myself, glad the Nexus examples use npm to provide some of the discover here :P
