### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '_state')

### ISSUE THREAD

**Issue by brielov** [remorses/genql#92]
Hi there, I've been trying to work with `subscription` and `react` but I keep getting the same error while subscribing inside of a `useEffect` hook.

```
Uncaught TypeError: Cannot read properties of undefined (reading '_state')
    at unsubscribe (Observable.js:208:16)
    at upload-progress-item.tsx:78:7
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23543:11)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushPassiveEffects (react-dom.development.js:23447:14)
    at react-dom.development.js:23324:11
```

There aren't too many examples on the website and I've also tried the subscriptions example in the repo but getting the same results, and react-extra-hooks seems deprecated since it doesn't point to any github repo nor has been updated for over two years.

```
const subscriber = (itemId: string) =>
  wsClient.chain.subscription.itemStatus({ itemId }).get({ ...everything });

  useEffect(() => {
    const { unsubscribe } = subscriber(item.id).subscribe({
      next(value) {
        console.log(value);
      },
    });
    return () => {
      unsubscribe();
    };
  }, [item.id]);
```

**Comment by brielov** [comment]
Any ideas?

**Comment by remorses** [comment]
v3 no longer has subscriptions, subscription may be implemented in the future again
